Adds potion amplifier reducing to certain foods
Evoslab/WhySoBlueberry pull request #1
Opened 2020-11-15 20:31 UTC by cosmicgelatin

2020-11-15 21:38 UTC, EltrutLikes requested changes
Since this is a Neapolitan addon, I think it would be a lot cleaner to use the classes provided by the mod already. I would create the effect, register it, and then add the effect to the items in the item properties section instead of creating entirely new classes just for the two items.

2020-11-15 21:38 UTC, EltrutLikes commented on src/main/java/com/evoslab/why_so_blueberry/common/block/BlueberryCakeBlock.java
> +            BlueberryMilkshakeItem.doEffect(player);
Instead of referencing the blueberry milkshake item to get the effect here, it would probably be better to create a separate class under the package `why_so_blueberry.common.potion.effects` for the effect and register it in a WhySoBlueberryEffects class under `why_so_blueberry.core.registry`.

2020-11-15 21:38 UTC, EltrutLikes commented on src/main/java/com/evoslab/why_so_blueberry/core/registry/WhySoBlueberryBlocks.java
> +    public static final RegistryObject<Block> BLUEBERRY_CAKE = HELPER.createBlockNoItem("blueberry_cake", ()->new BlueberryCakeBlock(WhySoBlueberryItems.Foods.BLUEBERRY_CAKE, Properties.BLUEBERRY_CAK
Instead of creating an entirely new class just for the BlueberryCakeBlock, use the FlavoredCakeBlock from Neapolitan and add the effect in the item properties section.

2020-11-15 21:38 UTC, EltrutLikes commented on src/main/java/com/evoslab/why_so_blueberry/core/registry/WhySoBlueberryItems.java
> +    public static final RegistryObject<Item> BLUEBERRY_MILKSHAKE = HELPER.createItem("blueberry_milkshake", ()->new BlueberryMilkshakeItem(new Item.Properties().food(Foods.BLUEBERRY_MILKSHAKE).maxSta
Same idea here, just use the MilkshakeItem from Neapolitan and add the effect in the item properties section.

2020-11-15 22:32 UTC, cosmicgelatin commented on src/main/java/com/evoslab/why_so_blueberry/common/block/BlueberryCakeBlock.java
> +            BlueberryMilkshakeItem.doEffect(player);
Milkshake effects and cake effects aren't really effets in the potion sense, they manipulate the effects list of an entity. What a MilkshakeItem from Neapolitan can do it hardcoded; it can all of a certain type of effect, or it can remove a random effect as with the Banana shake. If MilkshakeItem is used, the shake would have to do one of those things.

2020-11-16 00:25 UTC, EltrutLikes commented on src/main/java/com/evoslab/why_so_blueberry/common/block/BlueberryCakeBlock.java
> +            BlueberryMilkshakeItem.doEffect(player);
My bad, I must've read the plan for the milkshake wrong.

2020-11-16 00:30 UTC, cosmicgelatin commented on src/main/java/com/evoslab/why_so_blueberry/core/registry/WhySoBlueberryBlocks.java
> +    public static final RegistryObject<Block> BLUEBERRY_CAKE = HELPER.createBlockNoItem("blueberry_cake", ()->new BlueberryCakeBlock(WhySoBlueberryItems.Foods.BLUEBERRY_CAKE, Properties.BLUEBERRY_CAK
Same issue as with MilkshakeItem, FlavoredCakeBlock can only remove effects of a type or remove a random effect.

2020-11-16 00:30 UTC, cosmicgelatin commented on src/main/java/com/evoslab/why_so_blueberry/core/registry/WhySoBlueberryItems.java
> +    public static final RegistryObject<Item> BLUEBERRY_MILKSHAKE = HELPER.createItem("blueberry_milkshake", ()->new BlueberryMilkshakeItem(new Item.Properties().food(Foods.BLUEBERRY_MILKSHAKE).maxSta
^^

2020-11-16 00:35 UTC, EltrutLikes commented on src/main/java/com/evoslab/why_so_blueberry/common/item/BlueberryMilkshakeItem.java
> +    public static void doEffect(LivingEntity entity) {
I would move this method out of this class and into a separate class so that you don't reference this item in the cake class.

2020-11-16 00:58 UTC, cosmicgelatin commented on src/main/java/com/evoslab/why_so_blueberry/common/item/BlueberryMilkshakeItem.java
> +    public static void doEffect(LivingEntity entity) {
I think it's fine as it still makes sense when reading it. If more than 1 flavor of shake was added, I'd think creating a separate class might be good. But creating a class for a single static method with only case seems unnecessary.

2020-11-16 02:30 UTC, merged